export interface Product {
    id: string;
    imageUrl: string;
    name: string;       
    description: string;
    price: number;
    category?: string; // Optional category field
}

export const products: Product[] = [
    {
        id: '1',
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
        name: 'Premium Wireless Headphones',
        description: 'High-quality noise-cancelling wireless headphones with premium sound quality and 30-hour battery life. Perfect for music lovers and professionals.',
        price: 199.99,
    },
    {
        id: '2',
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
        name: 'Smart Watch Series 5',
        description: 'Advanced smartwatch with health monitoring, GPS, and water resistance. Features include heart rate tracking, sleep analysis, and fitness coaching.',
        price: 299.99,
    },
    {
        id: '3',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12',
        name: 'Professional Coffee Maker',
        description: 'Automatic coffee maker with built-in grinder, programmable settings, and thermal carafe. Makes perfect coffee every time.',
        price: 149.99,
    },
    {
        id: '4',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
        name: 'Limited Edition Running Shoes',
        description: 'Lightweight, breathable running shoes with advanced cushioning technology. Perfect for both casual runners and professional athletes.',
        price: 129.99,
    },
    {
        id: '5',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Designer Leather Wallet',
        description: 'Handcrafted genuine leather wallet with multiple card slots and RFID protection. Classic design that ages beautifully.',
        price: 79.99,
    },
    {
        id: '6',
        imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a',
        name: 'Smart Home Security Camera',
        description: '1080p HD security camera with night vision, motion detection, and two-way audio. Connects to your smartphone for remote monitoring.',
        price: 89.99,
    },
    {
        id: '7',
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
        name: 'Ergonomic Office Chair',
        description: 'Adjustable office chair with lumbar support, breathable mesh back, and premium padding. Designed for all-day comfort.',
        price: 249.99,
    },
    {
        id: '8',
        imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
        name: 'Designer Sunglasses',
        description: 'UV-protected polarized sunglasses with scratch-resistant lenses and lightweight frame. Perfect for everyday wear.',
        price: 159.99,
    },
    {
        id: '9',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Yoga Mat',
        description: 'Non-slip yoga mat with perfect thickness for comfort and stability. Includes carrying strap and alignment lines.',
        price: 49.99,
    },
    {
        id: '10',
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
        name: 'Professional Camera Lens',
        description: 'High-quality zoom lens for professional photography. Features image stabilization and weather sealing.',
        price: 899.99,
    },
    {
        id: '11',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12',
        name: 'Smart Air Purifier',
        description: 'HEPA air purifier with smart sensors and app control. Removes 99.97% of airborne particles and allergens.',
        price: 199.99,
    },
    {
        id: '12',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
        name: 'Wireless Gaming Mouse',
        description: 'High-precision gaming mouse with customizable RGB lighting and programmable buttons. Ultra-low latency connection.',
        price: 79.99,
    },
    {
        id: '13',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Mechanical Keyboard',
        description: 'RGB mechanical keyboard with customizable keys and premium switches. Perfect for gaming and typing.',
        price: 129.99,
    },
    {
        id: '14',
        imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a',
        name: 'Smart Water Bottle',
        description: 'Temperature-controlled water bottle with hydration tracking and reminders. Keeps drinks cold for 24 hours.',
        price: 39.99,
    },
    {
        id: '15',
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
        name: 'Portable Bluetooth Speaker',
        description: 'Waterproof Bluetooth speaker with 360-degree sound and 12-hour battery life. Perfect for outdoor adventures.',
        price: 89.99,
    },
    {
        id: '16',
        imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
        name: 'Smart Fitness Tracker',
        description: 'Advanced fitness tracker with heart rate monitoring, sleep tracking, and 7-day battery life.',
        price: 149.99,
    },
    {
        id: '17',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Wireless Earbuds',
        description: 'True wireless earbuds with active noise cancellation and premium sound quality. Includes charging case.',
        price: 179.99,
    },
    {
        id: '18',
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
        name: 'Smart Door Lock',
        description: 'Fingerprint and app-controlled smart lock with backup key. Includes auto-lock and guest access features.',
        price: 199.99,
    },
    {
        id: '19',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12',
        name: 'Robot Vacuum Cleaner',
        description: 'Smart robot vacuum with mapping technology and app control. Automatically returns to charging station.',
        price: 299.99,
    },
    {
        id: '20',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
        name: 'Smart Light Bulb Set',
        description: 'Color-changing smart bulbs with voice control and scheduling. Create the perfect ambiance for any occasion.',
        price: 49.99,
    },
    {
        id: '21',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Backpack',
        description: 'Water-resistant backpack with laptop compartment and multiple pockets. Perfect for work or travel.',
        price: 89.99,
    },
    {
        id: '22',
        imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a',
        name: 'Smart Thermostat',
        description: 'Learning thermostat that adapts to your schedule. Saves energy and can be controlled from anywhere.',
        price: 249.99,
    },
    {
        id: '23',
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
        name: 'Wireless Charging Pad',
        description: 'Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED indicator.',
        price: 39.99,
    },
    {
        id: '24',
        imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
        name: 'Smart Doorbell Camera',
        description: 'Video doorbell with motion detection and two-way audio. See and speak to visitors from anywhere.',
        price: 199.99,
    },
    {
        id: '25',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Watch',
        description: 'Automatic watch with sapphire crystal and stainless steel case. Water-resistant and elegant design.',
        price: 299.99,
    },
    {
        id: '26',
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
        name: 'Smart Scale',
        description: 'Body composition scale that tracks weight, BMI, and body fat percentage. Syncs with fitness apps.',
        price: 79.99,
    },
    {
        id: '27',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12',
        name: 'Wireless Gaming Headset',
        description: 'Surround sound gaming headset with noise-cancelling microphone and RGB lighting. Comfortable for long sessions.',
        price: 129.99,
    },
    {
        id: '28',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
        name: 'Smart Plug Set',
        description: 'Set of 4 smart plugs with energy monitoring and scheduling. Control devices from your smartphone.',
        price: 49.99,
    },
    {
        id: '29',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Bluetooth Speaker',
        description: 'Portable speaker with 360-degree sound and 20-hour battery life. Perfect for parties and outdoor use.',
        price: 199.99,
    },
    {
        id: '30',
        imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a',
        name: 'Smart Light Strip',
        description: 'Color-changing LED light strip with music sync and app control. Create dynamic lighting effects.',
        price: 39.99,
    },
    {
        id: '31',
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
        name: 'Wireless Power Bank',
        description: '20000mAh power bank with wireless charging and fast charging ports. Charges multiple devices simultaneously.',
        price: 69.99,
    },
    {
        id: '32',
        imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
        name: 'Smart Smoke Detector',
        description: 'Connected smoke and carbon monoxide detector with mobile alerts and self-testing features.',
        price: 119.99,
    },
    {
        id: '33',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Gaming Monitor',
        description: '27-inch 4K gaming monitor with 144Hz refresh rate and HDR support. Perfect for gaming and content creation.',
        price: 399.99,
    },
    {
        id: '34',
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
        name: 'Smart Window Blinds',
        description: 'Automated window blinds with scheduling and voice control. Adjusts based on sunlight and temperature.',
        price: 199.99,
    },
    {
        id: '35',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12',
        name: 'Wireless Gaming Controller',
        description: 'Ergonomic gaming controller with customizable buttons and RGB lighting. Compatible with multiple platforms.',
        price: 79.99,
    },
    {
        id: '36',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
        name: 'Smart Pet Feeder',
        description: 'Automated pet feeder with app control and portion control. Includes camera for remote monitoring.',
        price: 149.99,
    },
    {
        id: '37',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Soundbar',
        description: '3D surround sound soundbar with wireless subwoofer and voice control. Perfect for home theater setup.',
        price: 299.99,
    },
    {
        id: '38',
        imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a',
        name: 'Smart Plant Monitor',
        description: 'Plant care system that monitors soil moisture, light, and temperature. Sends alerts when plants need attention.',
        price: 49.99,
    },
    {
        id: '39',
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
        name: 'Wireless Security Camera',
        description: 'Battery-powered security camera with night vision and two-way audio. Stores footage in the cloud.',
        price: 129.99,
    },
    {
        id: '40',
        imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
        name: 'Smart Garage Door Opener',
        description: 'WiFi-enabled garage door opener with app control and scheduling. Includes battery backup.',
        price: 199.99,
    },
    {
        id: '41',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Gaming Chair',
        description: 'Ergonomic gaming chair with adjustable lumbar support and headrest. Includes footrest and armrests.',
        price: 299.99,
    },
    {
        id: '42',
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
        name: 'Smart Water Leak Detector',
        description: 'Wireless water leak detector with mobile alerts and temperature monitoring. Prevents water damage.',
        price: 39.99,
    },
    {
        id: '43',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12',
        name: 'Wireless Gaming Mouse Pad',
        description: 'RGB gaming mouse pad with wireless charging and USB hub. Perfect for gaming setup.',
        price: 59.99,
    },
    {
        id: '44',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
        name: 'Smart Air Quality Monitor',
        description: 'Air quality monitor that tracks pollutants, temperature, and humidity. Provides real-time alerts.',
        price: 89.99,
    },
    {
        id: '45',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Wireless Earbuds',
        description: 'True wireless earbuds with active noise cancellation and premium sound quality. Includes charging case.',
        price: 249.99,
    },
    {
        id: '46',
        imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a',
        name: 'Smart Door Sensor',
        description: 'Wireless door sensor with mobile alerts and activity history. Perfect for home security.',
        price: 29.99,
    },
    {
        id: '47',
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
        name: 'Wireless Gaming Headset Stand',
        description: 'RGB headset stand with USB hub and audio pass-through. Includes cable management.',
        price: 49.99,
    },
    {
        id: '48',
        imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
        name: 'Smart Window Sensor',
        description: 'Window sensor with temperature monitoring and mobile alerts. Helps with energy efficiency.',
        price: 34.99,
    },
    {
        id: '49',
        imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad',
        name: 'Premium Gaming Keyboard',
        description: 'Mechanical gaming keyboard with RGB lighting and programmable keys. Includes wrist rest.',
        price: 159.99,
    },
    {
        id: '50',
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
        name: 'Smart Motion Sensor',
        description: 'Wireless motion sensor with temperature monitoring and mobile alerts. Perfect for home automation.',
        price: 29.99,
    }
];